# librelane/runner:openlane
# OpenLane 1 birlesik imaji (Docker Hub efabless/openlane).
# Hub ornegi amd64; ARM host'ta build/pull sirasinda --platform=linux/amd64 kullanin.
FROM efabless/openlane:ci2504-dev-amd64

WORKDIR /work
CMD ["bash"]
